### ISSUE TITLE
Errors in Program

### ISSUE THREAD

**Issue by TDouch** [BlackHatsCS/Project-3#2]
When the program is run an error occurs.
Warning (from warnings module):
  File "H:\Project-3\Project-3\trapspawn.py", line 41
    global trapspawn
SyntaxWarning: name 'trapspawn' is assigned to before global declaration

**Comment by Mithellin** [comment]
Changed trapspawn to just trap and the error is gone now.

**Comment by Mithellin** [comment]
I broke it again, gonna look into this issue its same thing again.

**Comment by Mithellin** [comment]
I moved the "global trap" out of the "def spawn():" and the error doesn't come up anymore, not too sure if this has fixed it completely, we'll test it with the program later I guess
